version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:3306, rabbitmq:5672
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - db
      - rabbitmq

  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./scripts/db/dev.sql:/docker-entrypoint-initdb.d/dev.sql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  node_modules:
